input {
  file {
    path => "C:/Users/Doorsy/Desktop/SMSSpamCollection.csv"
    start_position => "beginning"
    sincedb_path => "nul"
  }
}

filter {
  csv {
    separator => ","
    columns => ["etiqueta", "mensaje"]
    skip_header => true
  }

  mutate {
    # Convertir la etiqueta a un campo de texto
    convert => { "etiqueta" => "string" }
    
    # Convertir el mensaje a un campo de texto
    convert => { "mensaje" => "string" }
    
    # Añadir un campo para indicar si es spam (para facilitar búsquedas)
    add_field => { 
      "es_spam" => "%{etiqueta}" 
    }
  }

  # Transformar el campo es_spam a booleano
  if [etiqueta] == "spam" {
    mutate {
      replace => { "es_spam" => "true" }
    }
  } else if [etiqueta] == "ham" {
    mutate {
      replace => { "es_spam" => "false" }
    }
  }

  # Añadir timestamp actual si no existe uno en los datos
  if ![timestamp] {
    mutate {
      add_field => { "timestamp" => "%{@timestamp}" }
    }
  }
}

output {
  elasticsearch {
    hosts => ["http://localhost:9200"]
    user => "elastic"
    password => "t0Ea5_=7OUUNz_0E*Em6"
    index => "kevin"
  }
  stdout { codec => rubydebug }
}